name: parabeac_chalg
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/parabeac_chalg/assets/images/1_16.png
    - packages/parabeac_chalg/assets/images/1_24.png
    - packages/parabeac_chalg/assets/images/1_31.png
    - packages/parabeac_chalg/assets/images/3_1003.png
    - packages/parabeac_chalg/assets/images/3_1007.png
    - packages/parabeac_chalg/assets/images/3_1009.png
    - packages/parabeac_chalg/assets/images/3_1015.png
    - packages/parabeac_chalg/assets/images/3_1020.png
    - packages/parabeac_chalg/assets/images/3_1022.png
    - packages/parabeac_chalg/assets/images/3_1024.png
    - packages/parabeac_chalg/assets/images/3_1025.png
    - packages/parabeac_chalg/assets/images/3_1027.png
    - packages/parabeac_chalg/assets/images/3_1028.png
    - packages/parabeac_chalg/assets/images/3_1029.png
    - packages/parabeac_chalg/assets/images/3_1030.png
    - packages/parabeac_chalg/assets/images/3_1037.png
    - packages/parabeac_chalg/assets/images/3_1043.png
    - packages/parabeac_chalg/assets/images/3_1052.png
    - packages/parabeac_chalg/assets/images/3_1053.png
    - packages/parabeac_chalg/assets/images/3_1056.png
    - packages/parabeac_chalg/assets/images/3_1059.png
    - packages/parabeac_chalg/assets/images/3_1062.png
    - packages/parabeac_chalg/assets/images/3_1064.png
    - packages/parabeac_chalg/assets/images/3_1093.png
    - packages/parabeac_chalg/assets/images/3_1094.png
    - packages/parabeac_chalg/assets/images/3_1097.png
    - packages/parabeac_chalg/assets/images/3_1099.png
    - packages/parabeac_chalg/assets/images/3_1101.png
    - packages/parabeac_chalg/assets/images/3_1102.png
    - packages/parabeac_chalg/assets/images/3_1106.png
    - packages/parabeac_chalg/assets/images/3_1107.png
    - packages/parabeac_chalg/assets/images/3_1113.png
    - packages/parabeac_chalg/assets/images/3_1115.png
    - packages/parabeac_chalg/assets/images/3_1116.png
    - packages/parabeac_chalg/assets/images/3_1118.png
    - packages/parabeac_chalg/assets/images/3_1119.png
    - packages/parabeac_chalg/assets/images/3_1120.png
    - packages/parabeac_chalg/assets/images/3_1121.png
    - packages/parabeac_chalg/assets/images/3_1122.png
    - packages/parabeac_chalg/assets/images/3_1126.png
    - packages/parabeac_chalg/assets/images/3_1131.png
    - packages/parabeac_chalg/assets/images/3_1137.png
    - packages/parabeac_chalg/assets/images/3_1138.png
    - packages/parabeac_chalg/assets/images/3_1147.png
    - packages/parabeac_chalg/assets/images/3_1148.png
    - packages/parabeac_chalg/assets/images/3_1151.png
    - packages/parabeac_chalg/assets/images/3_1153.png
    - packages/parabeac_chalg/assets/images/3_1165.png
    - packages/parabeac_chalg/assets/images/3_1166.png
    - packages/parabeac_chalg/assets/images/3_1171.png
    - packages/parabeac_chalg/assets/images/3_1175.png
    - packages/parabeac_chalg/assets/images/3_1179.png
    - packages/parabeac_chalg/assets/images/3_1183.png
    - packages/parabeac_chalg/assets/images/3_1187.png
    - packages/parabeac_chalg/assets/images/3_1193.png
    - packages/parabeac_chalg/assets/images/3_1198.png
    - packages/parabeac_chalg/assets/images/3_1205.png
    - packages/parabeac_chalg/assets/images/3_1207.png
    - packages/parabeac_chalg/assets/images/3_647.png
    - packages/parabeac_chalg/assets/images/3_649.png
    - packages/parabeac_chalg/assets/images/3_650.png
    - packages/parabeac_chalg/assets/images/3_652.png
    - packages/parabeac_chalg/assets/images/3_653.png
    - packages/parabeac_chalg/assets/images/3_654.png
    - packages/parabeac_chalg/assets/images/3_655.png
    - packages/parabeac_chalg/assets/images/3_656.png
    - packages/parabeac_chalg/assets/images/3_660.png
    - packages/parabeac_chalg/assets/images/3_665.png
    - packages/parabeac_chalg/assets/images/3_671.png
    - packages/parabeac_chalg/assets/images/3_672.png
    - packages/parabeac_chalg/assets/images/3_678.png
    - packages/parabeac_chalg/assets/images/3_682.png
    - packages/parabeac_chalg/assets/images/3_689.png
    - packages/parabeac_chalg/assets/images/3_697.png
    - packages/parabeac_chalg/assets/images/3_711.png
    - packages/parabeac_chalg/assets/images/3_712.png
    - packages/parabeac_chalg/assets/images/3_713.png
    - packages/parabeac_chalg/assets/images/3_714.png
    - packages/parabeac_chalg/assets/images/3_717.png
    - packages/parabeac_chalg/assets/images/3_732.png
    - packages/parabeac_chalg/assets/images/3_733.png
    - packages/parabeac_chalg/assets/images/3_734.png
    - packages/parabeac_chalg/assets/images/3_735.png
    - packages/parabeac_chalg/assets/images/3_736.png
    - packages/parabeac_chalg/assets/images/3_737.png
    - packages/parabeac_chalg/assets/images/3_738.png
    - packages/parabeac_chalg/assets/images/3_739.png
    - packages/parabeac_chalg/assets/images/3_740.png
    - packages/parabeac_chalg/assets/images/3_741.png
    - packages/parabeac_chalg/assets/images/3_742.png
    - packages/parabeac_chalg/assets/images/3_743.png
    - packages/parabeac_chalg/assets/images/3_744.png
    - packages/parabeac_chalg/assets/images/3_745.png
    - packages/parabeac_chalg/assets/images/3_746.png
    - packages/parabeac_chalg/assets/images/3_747.png
    - packages/parabeac_chalg/assets/images/3_748.png
    - packages/parabeac_chalg/assets/images/3_749.png
    - packages/parabeac_chalg/assets/images/3_750.png
    - packages/parabeac_chalg/assets/images/3_751.png
    - packages/parabeac_chalg/assets/images/3_752.png
    - packages/parabeac_chalg/assets/images/3_753.png
    - packages/parabeac_chalg/assets/images/3_754.png
    - packages/parabeac_chalg/assets/images/3_755.png
    - packages/parabeac_chalg/assets/images/3_756.png
    - packages/parabeac_chalg/assets/images/3_757.png
    - packages/parabeac_chalg/assets/images/3_758.png
    - packages/parabeac_chalg/assets/images/3_759.png
    - packages/parabeac_chalg/assets/images/3_760.png
    - packages/parabeac_chalg/assets/images/3_761.png
    - packages/parabeac_chalg/assets/images/3_762.png
    - packages/parabeac_chalg/assets/images/3_763.png
    - packages/parabeac_chalg/assets/images/3_764.png
    - packages/parabeac_chalg/assets/images/3_765.png
    - packages/parabeac_chalg/assets/images/3_766.png
    - packages/parabeac_chalg/assets/images/3_767.png
    - packages/parabeac_chalg/assets/images/3_768.png
    - packages/parabeac_chalg/assets/images/3_769.png
    - packages/parabeac_chalg/assets/images/3_770.png
    - packages/parabeac_chalg/assets/images/3_771.png
    - packages/parabeac_chalg/assets/images/3_772.png
    - packages/parabeac_chalg/assets/images/3_773.png
    - packages/parabeac_chalg/assets/images/3_774.png
    - packages/parabeac_chalg/assets/images/3_777.png
    - packages/parabeac_chalg/assets/images/3_778.png
    - packages/parabeac_chalg/assets/images/3_779.png
    - packages/parabeac_chalg/assets/images/3_780.png
    - packages/parabeac_chalg/assets/images/3_781.png
    - packages/parabeac_chalg/assets/images/3_782.png
    - packages/parabeac_chalg/assets/images/3_783.png
    - packages/parabeac_chalg/assets/images/3_784.png
    - packages/parabeac_chalg/assets/images/3_785.png
    - packages/parabeac_chalg/assets/images/3_786.png
    - packages/parabeac_chalg/assets/images/3_787.png
    - packages/parabeac_chalg/assets/images/3_788.png
    - packages/parabeac_chalg/assets/images/3_789.png
    - packages/parabeac_chalg/assets/images/3_790.png
    - packages/parabeac_chalg/assets/images/3_791.png
    - packages/parabeac_chalg/assets/images/3_792.png
    - packages/parabeac_chalg/assets/images/3_793.png
    - packages/parabeac_chalg/assets/images/3_794.png
    - packages/parabeac_chalg/assets/images/3_795.png
    - packages/parabeac_chalg/assets/images/3_796.png
    - packages/parabeac_chalg/assets/images/3_797.png
    - packages/parabeac_chalg/assets/images/3_798.png
    - packages/parabeac_chalg/assets/images/3_799.png
    - packages/parabeac_chalg/assets/images/3_800.png
    - packages/parabeac_chalg/assets/images/3_801.png
    - packages/parabeac_chalg/assets/images/3_802.png
    - packages/parabeac_chalg/assets/images/3_803.png
    - packages/parabeac_chalg/assets/images/3_804.png
    - packages/parabeac_chalg/assets/images/3_805.png
    - packages/parabeac_chalg/assets/images/3_806.png
    - packages/parabeac_chalg/assets/images/3_807.png
    - packages/parabeac_chalg/assets/images/3_808.png
    - packages/parabeac_chalg/assets/images/3_809.png
    - packages/parabeac_chalg/assets/images/3_810.png
    - packages/parabeac_chalg/assets/images/3_811.png
    - packages/parabeac_chalg/assets/images/3_812.png
    - packages/parabeac_chalg/assets/images/3_813.png
    - packages/parabeac_chalg/assets/images/3_814.png
    - packages/parabeac_chalg/assets/images/3_815.png
    - packages/parabeac_chalg/assets/images/3_816.png
    - packages/parabeac_chalg/assets/images/3_817.png
    - packages/parabeac_chalg/assets/images/3_818.png
    - packages/parabeac_chalg/assets/images/3_823.png
    - packages/parabeac_chalg/assets/images/3_824.png
    - packages/parabeac_chalg/assets/images/3_825.png
    - packages/parabeac_chalg/assets/images/3_826.png
    - packages/parabeac_chalg/assets/images/3_827.png
    - packages/parabeac_chalg/assets/images/3_828.png
    - packages/parabeac_chalg/assets/images/3_829.png
    - packages/parabeac_chalg/assets/images/3_830.png
    - packages/parabeac_chalg/assets/images/3_831.png
    - packages/parabeac_chalg/assets/images/3_832.png
    - packages/parabeac_chalg/assets/images/3_833.png
    - packages/parabeac_chalg/assets/images/3_834.png
    - packages/parabeac_chalg/assets/images/3_835.png
    - packages/parabeac_chalg/assets/images/3_836.png
    - packages/parabeac_chalg/assets/images/3_837.png
    - packages/parabeac_chalg/assets/images/3_838.png
    - packages/parabeac_chalg/assets/images/3_839.png
    - packages/parabeac_chalg/assets/images/3_840.png
    - packages/parabeac_chalg/assets/images/3_841.png
    - packages/parabeac_chalg/assets/images/3_842.png
    - packages/parabeac_chalg/assets/images/3_843.png
    - packages/parabeac_chalg/assets/images/3_844.png
    - packages/parabeac_chalg/assets/images/3_845.png
    - packages/parabeac_chalg/assets/images/3_846.png
    - packages/parabeac_chalg/assets/images/3_847.png
    - packages/parabeac_chalg/assets/images/3_848.png
    - packages/parabeac_chalg/assets/images/3_849.png
    - packages/parabeac_chalg/assets/images/3_850.png
    - packages/parabeac_chalg/assets/images/3_851.png
    - packages/parabeac_chalg/assets/images/3_852.png
    - packages/parabeac_chalg/assets/images/3_853.png
    - packages/parabeac_chalg/assets/images/3_854.png
    - packages/parabeac_chalg/assets/images/3_855.png
    - packages/parabeac_chalg/assets/images/3_856.png
    - packages/parabeac_chalg/assets/images/3_857.png
    - packages/parabeac_chalg/assets/images/3_858.png
    - packages/parabeac_chalg/assets/images/3_859.png
    - packages/parabeac_chalg/assets/images/3_860.png
    - packages/parabeac_chalg/assets/images/3_861.png
    - packages/parabeac_chalg/assets/images/3_862.png
    - packages/parabeac_chalg/assets/images/3_863.png
    - packages/parabeac_chalg/assets/images/3_864.png
    - packages/parabeac_chalg/assets/images/3_865.png
    - packages/parabeac_chalg/assets/images/3_866.png
    - packages/parabeac_chalg/assets/images/3_867.png
    - packages/parabeac_chalg/assets/images/3_868.png
    - packages/parabeac_chalg/assets/images/3_869.png
    - packages/parabeac_chalg/assets/images/3_870.png
    - packages/parabeac_chalg/assets/images/3_871.png
    - packages/parabeac_chalg/assets/images/3_872.png
    - packages/parabeac_chalg/assets/images/3_873.png
    - packages/parabeac_chalg/assets/images/3_874.png
    - packages/parabeac_chalg/assets/images/3_875.png
    - packages/parabeac_chalg/assets/images/3_876.png
    - packages/parabeac_chalg/assets/images/3_877.png
    - packages/parabeac_chalg/assets/images/3_878.png
    - packages/parabeac_chalg/assets/images/3_879.png
    - packages/parabeac_chalg/assets/images/3_880.png
    - packages/parabeac_chalg/assets/images/3_881.png
    - packages/parabeac_chalg/assets/images/3_882.png
    - packages/parabeac_chalg/assets/images/3_883.png
    - packages/parabeac_chalg/assets/images/3_884.png
    - packages/parabeac_chalg/assets/images/3_885.png
    - packages/parabeac_chalg/assets/images/3_886.png
    - packages/parabeac_chalg/assets/images/3_887.png
    - packages/parabeac_chalg/assets/images/3_888.png
    - packages/parabeac_chalg/assets/images/3_889.png
    - packages/parabeac_chalg/assets/images/3_890.png
    - packages/parabeac_chalg/assets/images/3_891.png
    - packages/parabeac_chalg/assets/images/3_892.png
    - packages/parabeac_chalg/assets/images/3_893.png
    - packages/parabeac_chalg/assets/images/3_894.png
    - packages/parabeac_chalg/assets/images/3_895.png
    - packages/parabeac_chalg/assets/images/3_896.png
    - packages/parabeac_chalg/assets/images/3_897.png
    - packages/parabeac_chalg/assets/images/3_898.png
    - packages/parabeac_chalg/assets/images/3_899.png
    - packages/parabeac_chalg/assets/images/3_900.png
    - packages/parabeac_chalg/assets/images/3_901.png
    - packages/parabeac_chalg/assets/images/3_902.png
    - packages/parabeac_chalg/assets/images/3_903.png
    - packages/parabeac_chalg/assets/images/3_904.png
    - packages/parabeac_chalg/assets/images/3_905.png
    - packages/parabeac_chalg/assets/images/3_906.png
    - packages/parabeac_chalg/assets/images/3_907.png
    - packages/parabeac_chalg/assets/images/3_908.png
    - packages/parabeac_chalg/assets/images/3_909.png
    - packages/parabeac_chalg/assets/images/3_914.png
    - packages/parabeac_chalg/assets/images/3_945.png
    - packages/parabeac_chalg/assets/images/3_946.png
    - packages/parabeac_chalg/assets/images/3_947.png
    - packages/parabeac_chalg/assets/images/3_957.png
    - packages/parabeac_chalg/assets/images/3_958.png
    - packages/parabeac_chalg/assets/images/3_961.png
    - packages/parabeac_chalg/assets/images/3_981.png
